#!/usr/bin/env python3
"""Test bootstrap VM execution (not just pipeline).

Validates that the bootstrap interpreter.hto execute() function can
actually run generated bytecode — not just tokenize→parse→compile.
"""
import os, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
PARENT = os.path.abspath(os.path.join(ROOT, '..'))
if PARENT not in sys.path:
    sys.path.insert(0, PARENT)

from lexer import Lexer
from parser import Parser
from interpreter import Interpreter


def load_hto(path):
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()


def run_hsharp_source(src, interp):
    lexer = Lexer(src)
    parser = Parser(lexer)
    ast = parser.parse()
    return interp.interpret(ast)


def main():
    interp = Interpreter()
    print("=" * 60)
    print("  Bootstrap VM Execution Test")
    print("=" * 60)
    print()

    # Load bootstrap components
    components = ['tokenize', 'parser', 'compiler', 'interpreter']
    for comp in components:
        path = os.path.join(ROOT, f'{comp}.hto')
        if os.path.exists(path):
            print(f"  Loading {comp}.hto...")
            run_hsharp_source(load_hto(path), interp)
        else:
            print(f"  WARNING: {comp}.hto not found")
            sys.exit(1)
    print("  Bootstrap components loaded.")
    print()

    results = []

    def run_test(name, src, expected_output=None):
        print(f"[Test] {name}")
        try:
            # Capture print output
            import io
            from contextlib import redirect_stdout
            buf = io.StringIO()
            with redirect_stdout(buf):
                run_hsharp_source(src, interp)
            output = buf.getvalue().strip()
            if expected_output is not None:
                if output == expected_output:
                    print(f"  PASS (output: {output})")
                    results.append((name, True, ''))
                else:
                    print(f"  FAIL: expected '{expected_output}', got '{output}'")
                    results.append((name, False, f'expected {expected_output!r}, got {output!r}'))
            else:
                print(f"  OK (output: {output[:80]})")
                results.append((name, True, output))
        except Exception as e:
            print(f"  ERROR: {e}")
            results.append((name, False, str(e)))

    # Test 1: simple arithmetic via bootstrap pipeline
    test1 = '''
let src1 = "let x = 40 + 2;\\nprint(x);\\n";
let t1 = tokenize(src1);
let a1 = parse(t1);
let bc1 = compile(a1);
execute(bc1, {});
'''
    run_test("simple arithmetic (40+2=42)", test1, "42")

    # Test 2: function call
    test2 = '''
let src2 = "fn square(n) { return n * n; }\\nlet r = square(7);\\nprint(r);\\n";
let t2 = tokenize(src2);
let a2 = parse(t2);
let bc2 = compile(a2);
execute(bc2, {});
'''
    run_test("function call (square(7)=49)", test2, "49")

    # Test 3: if/else
    test3 = '''
let src3 = "let x = 5;\\nif (x > 3) { print(\\\"yes\\\"); } else { print(\\\"no\\\"); }\\n";
let t3 = tokenize(src3);
let a3 = parse(t3);
let bc3 = compile(a3);
execute(bc3, {});
'''
    run_test("if/else (yes)", test3, "yes")

    # Test 4: while loop
    test4 = '''
let src4 = "let i = 0; let s = 0; while (i < 5) { s = s + i; i = i + 1; } print(s);\\n";
let t4 = tokenize(src4);
let a4 = parse(t4);
let bc4 = compile(a4);
execute(bc4, {});
'''
    run_test("while loop (sum 0..4=10)", test4, "10")

    # Test 5: string concatenation
    test5 = '''
let src5 = "let a = \\\"Hello\\\"; let b = \\\" World\\\"; print(a + b);\\n";
let t5 = tokenize(src5);
let a5 = parse(t5);
let bc5 = compile(a5);
execute(bc5, {});
'''
    run_test("string concat (Hello World)", test5, "Hello World")

    # Test 6: list operations
    test6 = '''
let src6 = "let lst = [1, 2, 3]; print(lst[0]); print(lst[2]);\\n";
let t6 = tokenize(src6);
let a6 = parse(t6);
let bc6 = compile(a6);
execute(bc6, {});
'''
    run_test("list indexing (1 then 3)", test6, "1\n3")

    # Summary
    print()
    print("=" * 60)
    passed = sum(1 for _, ok, _ in results if ok)
    total = len(results)
    for name, ok, err in results:
        status = "PASS" if ok else "FAIL"
        print(f"  {name:40s} : {status}")
        if not ok:
            print(f"    {err[:100]}")
    print()
    print(f"  {passed}/{total} tests passed")
    if passed == total:
        print("  Bootstrap VM execution: SUCCESS")
    else:
        print("  Bootstrap VM execution: SOME FAILURES")
    print("=" * 60)
    return 0 if passed == total else 1


if __name__ == '__main__':
    sys.exit(main())
